.TH "source/1_APP Directory Reference" 3 "Fri Nov 15 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/1_APP Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmtb\&.c\fP"
.br
.RI "MTB initialization file\&. "
.ti -1c
.RI "file \fBsemihost_hardfault\&.c\fP"
.br
.ti -1c
.RI "file \fBSmartLock\&.c\fP"
.br
.RI "Application entry point\&. "
.in -1c
