.TH "source/1_APP/semihost_hardfault.c" 3 "Fri Nov 15 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/1_APP/semihost_hardfault.c
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__attribute__\fP ((naked))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__attribute__ ((naked))"

.PP
Definition at line 70 of file semihost_hardfault\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
