.TH "source/1_APP/SmartLock.c" 3 "Fri Nov 15 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
source/1_APP/SmartLock.c \- Application entry point\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'board\&.h'\fP
.br
\fC#include 'peripherals\&.h'\fP
.br
\fC#include 'pin_mux\&.h'\fP
.br
\fC#include 'clock_config\&.h'\fP
.br
\fC#include 'MKL27Z644\&.h'\fP
.br
\fC#include 'fsl_debug_console\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application entry point\&. 


.PP
Definition in file \fBSmartLock\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 49 of file SmartLock\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
